workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        APP_ID: "adc627"
        BUNDLE_ID: "com.lovegpt.app"
      flutter: stable
      xcode: "16.3"
    scripts:
      - name: Set up signing
        script: |
          echo $CM_CERTIFICATE | base64 --decode > certificate.p12
          echo $CM_PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision

          # Create and unlock a keychain
          security create-keychain -p $CERT_PASSWORD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $CERT_PASSWORD build.keychain
          security set-keychain-settings build.keychain

          # Import certificate
          security import certificate.p12 -k build.keychain -P $CERT_PASSWORD -T /usr/bin/codesign

          # List keychains to verify
          security list-keychains

      - name: Build iOS Release
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: "${APPLE_ID}"
        password: "${APP_SPECIFIC_PASSWORD}"
