workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - ios-credentials  # This line is critical — it pulls from the team-level group
      vars:
        BUNDLE_ID: "com.lovegpt.app"
      flutter: stable
      xcode: "16.3"
    scripts:
      - name: Set up signing
        script: |
          echo $CM_CERTIFICATE | base64 --decode > certificate.p12
          echo $CM_PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision

          security create-keychain -p "$CERTIFICATE_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$CERTIFICATE_PASSWORD" build.keychain
          security set-keychain-settings build.keychain

          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains

      - name: Build iOS Release
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: "$APPLE_ID"
        password: "$APP_SPECIFIC_PASSWORD"
        submit_to_testflight: true
        submit_to_app_store: false
