workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - ios-credentials
      vars:
        BUNDLE_ID: "com.lovegpt.app"
      flutter: stable
      xcode: "16.3"
    scripts:
      - name: Set up signing
        script: |
          echo $CM_CERTIFICATE | base64 --decode > certificate.p12
          echo $CM_PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision

          security create-keychain -p "$CERTIFICATE_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$CERTIFICATE_PASSWORD" build.keychain
          security set-keychain-settings build.keychain

          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains

      - name: Build iOS Release
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
   publishing:
  app_store_connect:
    key_id: VZ5MF87W4F
    issuer_id: 360c6bf7-7101-4beb-b2cb-8463fd743cfd
    private_key: $APP_STORE_PRIVATE_KEY
    submit_to_testflight: true
    submit_to_app_store: false
