name: lovegpt_mobileapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Downgraded to compatible nanopb range)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.8
  firebase_messaging: ^15.2.6


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/src/assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - lib/src/assets/logo.png
    - lib/src/assets/aria_avatar.png
    - lib/src/assets/splash.png
    - lib/src/assets/icon.png
    - lib/src/assets/favicon.png
    - lib/src/assets/adaptive_icon.png

  fonts:
    - family: space_mono
      fonts:
        - asset: lib/src/assets/fonts/spacemono_regular.ttf
        - asset: lib/src/assets/fonts/spacemono_bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/spacemono_italic.ttf
          style: italic
        - asset: lib/src/assets/fonts/spacemono_bolditalic.ttf
          weight: 700
          style: italic

dependency_overrides:
  firebase_core: ^3.13.1
