name: lovegpt_mobileapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0      # Update to Firebase Core for Flutter (v3.x.x)
  firebase_auth: ^5.5.3       # Firebase Auth for authentication
  firebase_database: ^11.3.5  # Firebase Realtime Database
  firebase_storage: ^12.4.5   # Firebase Storage
  firebase_messaging: ^15.2.5 # Firebase Messaging (latest version compatible with firebase_core v3.x.x)
  cupertino_icons: ^1.0.8     # Cupertino icons for iOS style icons
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0       # Flutter lints for good coding practices

flutter:
  uses-material-design: true  # Material Design support for your app
  
  # For adding assets to your app (uncomment and add if needed)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Custom fonts (uncomment and add if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

dependency_overrides:
  firebase_core: ^3.13.0  # Updated to match firebase_messaging version compatibility
